version: '3.9'

services:
  postgres:
    container_name: postgres
    env_file: ${ENV_FILE}
    image: postgres:14
    shm_size: 2gb
    restart: always
    volumes: 
      - postgres_vol:/var/lib/postgresql/data:cached
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - net
      - ergopad-net

  redis:
    container_name: redis
    env_file: ${ENV_FILE}
    image: redis
    volumes: 
      - redis_vol:/data # redis persistence
    ports: 
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - net
      - ergopad-net
    entrypoint: redis-server --appendonly yes

volumes:
  postgres_vol:
  redis_vol:

networks:
  net:
    driver: bridge
  ergopad-net:
    external: true
